// <auto-generated />
using System;
using Eticaret.Persistence.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eticaret.Web.Mvc.Migrations
{
    [DbContext(typeof(EticaretDbContext))]
    [Migration("20240317195418_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Eticaret.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(100),
                            ProductId = 1,
                            Quantity = (byte)1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(100),
                            ProductId = 3,
                            Quantity = (byte)1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 2,
                            Quantity = (byte)3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 4,
                            Quantity = (byte)1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 5,
                            Quantity = (byte)1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 6,
                            Quantity = (byte)3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 7,
                            Quantity = (byte)1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 8,
                            Quantity = (byte)1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 9,
                            Quantity = (byte)3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(110),
                            ProductId = 3,
                            Quantity = (byte)1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 7,
                            Quantity = (byte)1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 8,
                            Quantity = (byte)3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 2,
                            Quantity = (byte)1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 1,
                            Quantity = (byte)1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 3,
                            Quantity = (byte)3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(120),
                            ProductId = 2,
                            Quantity = (byte)3,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconCssClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "pink",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9840),
                            Name = "dress"
                        },
                        new
                        {
                            Id = 2,
                            Color = "red",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9840),
                            Name = "jean"
                        },
                        new
                        {
                            Id = 3,
                            Color = "blue",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9840),
                            Name = "Sweatshirt"
                        },
                        new
                        {
                            Id = 4,
                            Color = "yellow",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9840),
                            Name = "Sweatpants"
                        },
                        new
                        {
                            Id = 5,
                            Color = "black",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9850),
                            Name = "Jumper"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9850),
                            Name = "Cardigan"
                        },
                        new
                        {
                            Id = 7,
                            Color = "gray",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9850),
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = 8,
                            Color = "darkred",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9850),
                            Name = "Trousers"
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9850),
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 10,
                            Color = "white",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9860),
                            Name = "T-shirt"
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "456 Elm St",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(70),
                            OrderCode = "ORD001",
                            UserId = 9
                        },
                        new
                        {
                            Id = 2,
                            Address = "789 Oak St",
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(70),
                            OrderCode = "ORD002",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(80),
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = (byte)2,
                            SellerId = 11,
                            UnitPrice = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(90),
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = (byte)1,
                            SellerId = 12,
                            UnitPrice = 19.99m
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StockAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9870),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 1",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9930),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 2",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9930),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 3",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9930),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 4",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9930),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 5",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9940),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 6",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9940),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 7",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9940),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 8",
                            Price = 10m,
                            SellerId = 11,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9940),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 9",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9950),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 10",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9950),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 11",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9950),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 12",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9960),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 13",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9960),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 14",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9960),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 15",
                            Price = 10m,
                            SellerId = 13,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9960),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 16",
                            Price = 10m,
                            SellerId = 13,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9970),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 17",
                            Price = 10m,
                            SellerId = 13,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9970),
                            Details = "ürün açıklama",
                            Enabled = true,
                            IsConfirmed = true,
                            Name = "Product 18",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9970),
                            Details = "ürün açıklama",
                            Enabled = false,
                            IsConfirmed = true,
                            Name = "Product 19",
                            Price = 10m,
                            SellerId = 12,
                            StockAmount = (byte)10
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.ProductComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StarCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(20),
                            IsConfirmed = true,
                            ProductId = 1,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(20),
                            IsConfirmed = true,
                            ProductId = 2,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 3,
                            StarCount = (byte)3,
                            Text = "Great product!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 4,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 5,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 6,
                            StarCount = (byte)1,
                            Text = "Great product!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 7,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(30),
                            IsConfirmed = true,
                            ProductId = 8,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 9,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 10,
                            StarCount = (byte)4,
                            Text = "Great product!",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 11,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 12,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 13,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(40),
                            IsConfirmed = true,
                            ProductId = 14,
                            StarCount = (byte)5,
                            Text = "Great product!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(50),
                            IsConfirmed = true,
                            ProductId = 15,
                            StarCount = (byte)4,
                            Text = "Nice product!",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local),
                            ProductId = 1,
                            SellerId = 11,
                            Url = "https://example.com/image1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 117, DateTimeKind.Local).AddTicks(10),
                            ProductId = 2,
                            SellerId = 11,
                            Url = "https://example.com/image2.jpg"
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9680),
                            Name = "seller"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9700),
                            Name = "buyer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9700),
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9730),
                            Email = "aysenur@aydin.com",
                            Enabled = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "123456",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9740),
                            Email = "ays2@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur4",
                            LastName = "Aydın4",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9740),
                            Email = "ays3@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur5",
                            LastName = "Aydın5",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9740),
                            Email = "ays4@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur6",
                            LastName = "Aydın6",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9750),
                            Email = "ays5@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur7",
                            LastName = "Aydın7",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9750),
                            Email = "ays6@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur4",
                            LastName = "Aydın4",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9750),
                            Email = "ays7@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur5",
                            LastName = "Aydın5",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9750),
                            Email = "ays8@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur6",
                            LastName = "Aydın6",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9760),
                            Email = "ays9@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur7",
                            LastName = "Aydın7",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9760),
                            Email = "ays10@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur2",
                            LastName = "Aydın2",
                            Password = "123456",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Seller", b =>
                {
                    b.HasBaseType("Eticaret.Domain.User");

                    b.HasDiscriminator().HasValue("Seller");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9780),
                            Email = "ays11@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur5",
                            LastName = "Aydın5",
                            Password = "123456",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9790),
                            Email = "ays12@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur6",
                            LastName = "Aydın6",
                            Password = "123456",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 3, 17, 22, 54, 18, 116, DateTimeKind.Local).AddTicks(9790),
                            Email = "ays13@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur7",
                            LastName = "Aydın7",
                            Password = "123456",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.CartItem", b =>
                {
                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.User", "UserFk")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.HasOne("Eticaret.Domain.User", "UserFk")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("Eticaret.Domain.OrderItem", b =>
                {
                    b.HasOne("Eticaret.Domain.Order", "OrderFk")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Seller", "SellerFk")
                        .WithMany("OrderItems")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderFk");

                    b.Navigation("ProductFk");

                    b.Navigation("SellerFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.HasOne("Eticaret.Domain.Category", "CategoryFk")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Seller", "SellerFk")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryFk");

                    b.Navigation("SellerFk");
                });

            modelBuilder.Entity("Eticaret.Domain.ProductComment", b =>
                {
                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.User", "UserFk")
                        .WithMany("ProductComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("Eticaret.Domain.ProductImage", b =>
                {
                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Seller", "SellerFk")
                        .WithMany("ProductImages")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFk");

                    b.Navigation("SellerFk");
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.HasOne("Eticaret.Domain.Role", "RoleFk")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("Eticaret.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("Eticaret.Domain.Seller", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
