// <auto-generated />
using System;
using Eticaret.Persistence.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eticaret.Web.Mvc.Migrations
{
    [DbContext(typeof(EticaretDbContext))]
    partial class EticaretDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Eticaret.Domain.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Eticaret.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Eticaret.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconCssClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "pink",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2420),
                            IconCssClass = "",
                            Name = "dress"
                        },
                        new
                        {
                            Id = 2,
                            Color = "red",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2450),
                            IconCssClass = "",
                            Name = "jean"
                        },
                        new
                        {
                            Id = 3,
                            Color = "blue",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2460),
                            IconCssClass = "",
                            Name = "Sweatshirt"
                        },
                        new
                        {
                            Id = 4,
                            Color = "yellow",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2460),
                            IconCssClass = "",
                            Name = "Sweatpants"
                        },
                        new
                        {
                            Id = 5,
                            Color = "black",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2490),
                            IconCssClass = "",
                            Name = "Jumper"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2490),
                            IconCssClass = "",
                            Name = "Cardigan"
                        },
                        new
                        {
                            Id = 7,
                            Color = "gray",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2500),
                            IconCssClass = "",
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = 8,
                            Color = "darkred",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2500),
                            IconCssClass = "",
                            Name = "Trousers"
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2500),
                            IconCssClass = "",
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 10,
                            Color = "white",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2500),
                            IconCssClass = "",
                            Name = "T-shirt"
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Eticaret.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StockAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2570),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 1",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2580),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 2",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2580),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 3",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2580),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 4",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2580),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 5",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2590),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 6",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2590),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 7",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2590),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 8",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2590),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 9",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2600),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 10",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2600),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 11",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2600),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 12",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2600),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 13",
                            Price = 10m,
                            SellerId = 2,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2600),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 14",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2610),
                            Details = "ürün açıklama",
                            Enabled = true,
                            Name = "Product 15",
                            Price = 10m,
                            SellerId = 1,
                            StockAmount = (byte)10
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.ProductComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StarCount")
                        .HasMaxLength(5)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Eticaret.Domain.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Eticaret.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2550),
                            Name = "seller"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2550),
                            Name = "buyer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2550),
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2630),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Admin",
                            Password = "123456",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2630),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur4",
                            LastName = "Aydın4",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2630),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur5",
                            LastName = "Aydın5",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2640),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur6",
                            LastName = "Aydın6",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2640),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur7",
                            LastName = "Aydın7",
                            Password = "123456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2640),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur2",
                            LastName = "Aydın2",
                            Password = "123456",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.Seller", b =>
                {
                    b.HasBaseType("Eticaret.Domain.User");

                    b.Property<string>("Adress")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long>("CallNumber")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Seller");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2660),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur1",
                            LastName = "Aydın1",
                            Password = "123456",
                            RoleId = 1,
                            Adress = "Bursa",
                            CallNumber = 5552552525L
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 9, 10, 59, 10, 691, DateTimeKind.Local).AddTicks(2660),
                            Email = "ays@ayd.com",
                            Enabled = true,
                            FirstName = "Ayşenur3",
                            LastName = "Aydın3",
                            Password = "123456",
                            RoleId = 1,
                            Adress = "Bursa",
                            CallNumber = 5552552525L
                        });
                });

            modelBuilder.Entity("Eticaret.Domain.CartItem", b =>
                {
                    b.HasOne("Eticaret.Domain.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.HasOne("Eticaret.Domain.User", "UserFk")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("Eticaret.Domain.OrderItem", b =>
                {
                    b.HasOne("Eticaret.Domain.Order", "OrderFk")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderFk");

                    b.Navigation("ProductFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.HasOne("Eticaret.Domain.Category", "CategoryFk")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Seller", "SellerFk")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryFk");

                    b.Navigation("SellerFk");
                });

            modelBuilder.Entity("Eticaret.Domain.ProductComment", b =>
                {
                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.User", "UserFk")
                        .WithMany("ProductComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("Eticaret.Domain.ProductImage", b =>
                {
                    b.HasOne("Eticaret.Domain.Product", "ProductFk")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eticaret.Domain.Seller", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("SellerId");

                    b.Navigation("ProductFk");
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.HasOne("Eticaret.Domain.Cart", "CartFk")
                        .WithMany()
                        .HasForeignKey("CartId");

                    b.HasOne("Eticaret.Domain.Role", "RoleFk")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartFk");

                    b.Navigation("RoleFk");
                });

            modelBuilder.Entity("Eticaret.Domain.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Eticaret.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Eticaret.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Eticaret.Domain.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("Eticaret.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eticaret.Domain.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("Eticaret.Domain.Seller", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
